# !/usr/bin/python
# -*- coding: utf-8 -*-
"""
    gsliu 2017-05-27
    
"""
comends = r'''
            system-view,
            switchto context %(name)s,
            system-view,
            ip vpn-instance mgmt,
            route-distinguisher 10000:1,
            interface GigabitEthernet1/0/0,
            ip binding vpn-instance mgmt,
            ip address %(ip1)s 24,
            interface GigabitEthernet2/0/0,
            ip binding vpn-instance mgmt,
            ip address %(ip2)s 24,
            security-zone name dci,
            import interface Reth1,
            security-zone name inside,
            import interface Reth2,
            security-zone name outside,
            import interface Reth22,
            security-zone name ext,
            import interface Reth23,
            security-zone name Management,
            import interface GigabitEthernet1/0/0,
            import interface GigabitEthernet2/0/0,
            line vty 0 4,
            authentication-mode scheme,
            ip route-static 0.0.0.0 0 10.252.35.193,
            ip route-static 172.16.0.0 16 10.252.35.129,
            ip route-static vpn-instance mgmt 0.0.0.0 0 172.16.246.254,
            ip route-static vpn-instance mgmt 0.0.0.0 0 172.16.247.254,
            session synchronization enable,
            local-user %(user)s class manage,
            password simple %(pwd)s,
            service-type ssh telnet http https,
            authorization-attribute user-role level-15,
            netconf soap http enable,
            netconf soap https enable,
            ip http enable,
            ip https enable,
            telnet server enable,
            ssh server enable,
            radius scheme travelsky,
            primary authentication 10.6.177.230 vpn-instance mgmt,
            primary accounting 10.6.177.230 vpn-instance mgmt,
            secondary authentication 10.6.177.231 vpn-instance mgmt,
            secondary accounting 10.6.177.231 vpn-instance mgmt,
            key authentication cipher $c$3$MsFCcHbDX/C8zqTanHjYRhdzH+7LXmM=,
            key accounting cipher $c$3$CQxzk3WMxjqXbVT8ghdwKk/9nM1Mj+M=,
            user-name-format without-domain,
            nas-ip %(nasip)s,
            vpn-instance mgmt,
            domain system,
            domain travelsky,
            authentication login radius-scheme travelsky,
            authorization login radius-scheme travelsky,
            accounting login radius-scheme travelsky,
            domain default enable travelsky,
            exit,
            exit,
            exit,
            exit
            '''
